title: <p align="center"> Trang Thanh Phúc </p>

# logo: /assets/img/headshot_circle.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/trangthanhphuc">GitHub</a>
  </p>

## Education
- SGU - SAI GON UNIVERSITY 
- MAJOR - SOFTWARE ENGINEER
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
