title: <p align="center"> Trang Thanh Phúc </p>

logo: /assets/img/logo.jpg
description: <p align="center">
  <a href="assets/img/cv.pdf">Resume</a> |
  <a href="https://github.com/trangthanhphuc">GitHub</a>
  </p>
  ** FRONTEND DEVELOPMENT **

  </p>

theme: jekyll-theme-minimal
